# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171223_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientmapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mapping_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorpatientmapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mapping_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
