# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171223_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientmapping',
            name='check_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
