# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctorpatientmapping_hospital_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
