# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientmapping',
            name='hospital_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpatientmapping',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Checked-up')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
