# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171225_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientmapping',
            name='hospital_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hospital_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
