# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171225_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experiance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
