# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_speciality_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consultency_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
