# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_consultency_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='speciality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Specialities', unique=True),
        ),
    ]
